steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/${PROJECT_ID}/node-app:${SHORT_SHA}', '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/${PROJECT_ID}/node-app:${SHORT_SHA}']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'node-app'  # Service Name
      - '--image=gcr.io/${PROJECT_ID}/node-app:${SHORT_SHA}'
      - '--platform=managed'
      - '--region=us-central1'
      - '--allow-unauthenticated'
      - '--project=${PROJECT_ID}'  # Explicitly define project

images:
  - 'gcr.io/${PROJECT_ID}/node-app:${SHORT_SHA}'

substitutions:
  _PROJECT_ID: "ci-cd-453709"  # Replace with your actual Project ID
